/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package weather.station;
@org.apache.avro.specific.AvroGenerated
public enum BatteryStatus implements org.apache.avro.generic.GenericEnumSymbol<BatteryStatus> {
  low, medium, high  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BatteryStatus\",\"namespace\":\"weather.station\",\"symbols\":[\"low\",\"medium\",\"high\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
